const navMenu=document.getElementById("nav-menu"),navToggle=document.getElementById("nav-toggle"),navClose=document.getElementById("nav-close");
navToggle.addEventListener("click",()=>{navMenu.classList.add("open");document.body.classList.add("no-scroll")});
navClose.addEventListener("click",()=>{navMenu.classList.remove("open");document.body.classList.remove("no-scroll")});
document.querySelectorAll(".nav-link").forEach(link=>link.addEventListener("click",()=>{navMenu.classList.remove("open");document.body.classList.remove("no-scroll")}));
const header=document.getElementById("header");window.addEventListener("scroll",()=>{header.classList.toggle("scrolled",window.scrollY>30)});
const themeToggle=document.getElementById("theme-toggle"),savedTheme=localStorage.getItem("roast-theme");
if(savedTheme==="dark"){document.body.classList.add("dark");themeToggle.textContent="☀"}
themeToggle.addEventListener("click",()=>{document.body.classList.toggle("dark");const isDark=document.body.classList.contains("dark");themeToggle.textContent=isDark?"☀":"☾";localStorage.setItem("roast-theme",isDark?"dark":"light")});
const filters=document.querySelectorAll(".filter"),products=document.querySelectorAll(".product-card");
filters.forEach(filter=>filter.addEventListener("click",()=>{filters.forEach(btn=>btn.classList.remove("active"));filter.classList.add("active");const category=filter.dataset.category;products.forEach(product=>product.style.display=category==="all"||product.dataset.category===category?"":"none")}));
let cart=[];const cartElement=document.getElementById("cart"),cartOpen=document.getElementById("cart-open"),cartClose=document.getElementById("cart-close"),overlay=document.getElementById("overlay"),cartItems=document.getElementById("cart-items"),cartCount=document.getElementById("cart-count"),cartTotal=document.getElementById("cart-total");
function openCart(){cartElement.classList.add("open");overlay.classList.add("active");document.body.classList.add("no-scroll")}
function closeCart(){cartElement.classList.remove("open");overlay.classList.remove("active");document.body.classList.remove("no-scroll")}
cartOpen.addEventListener("click",openCart);cartClose.addEventListener("click",closeCart);overlay.addEventListener("click",closeCart);
document.querySelectorAll(".add-btn").forEach(button=>button.addEventListener("click",()=>{const card=button.closest(".product-card"),item={name:card.dataset.name,price:Number(card.dataset.price),image:card.dataset.image},existing=cart.find(cartItem=>cartItem.name===item.name);existing?existing.quantity++:cart.push({...item,quantity:1});updateCart();openCart()}));
function updateCart(){if(cart.length===0){cartItems.innerHTML=`<div class="empty-cart"><div>🛒</div><h3>Your cart is empty</h3><p>Add something delicious from the menu.</p></div>`}else{cartItems.innerHTML=cart.map((item,index)=>`<div class="cart-item"><img src="${item.image}" alt="${item.name}"><div><h4>${item.name}</h4><div class="cart-item-price">PKR ${item.price.toLocaleString()}</div><div class="quantity"><button onclick="changeQuantity(${index},-1)">−</button><span>${item.quantity}</span><button onclick="changeQuantity(${index},1)">+</button></div></div><button class="remove-item" onclick="removeItem(${index})">Remove</button></div>`).join("")}const quantity=cart.reduce((sum,item)=>sum+item.quantity,0),total=cart.reduce((sum,item)=>sum+item.price*item.quantity,0);cartCount.textContent=quantity;cartTotal.textContent=`PKR ${total.toLocaleString()}`}
function changeQuantity(index,amount){cart[index].quantity+=amount;if(cart[index].quantity<=0)cart.splice(index,1);updateCart()}
function removeItem(index){cart.splice(index,1);updateCart()}
const checkoutButton=document.getElementById("checkout"),checkoutModal=document.getElementById("checkout-modal"),checkoutClose=document.getElementById("checkout-close"),checkoutSummary=document.getElementById("checkout-summary"),checkoutTotal=document.getElementById("checkout-total"),placeOrder=document.getElementById("place-order");
checkoutButton.addEventListener("click",()=>{if(cart.length===0){alert("Your cart is empty.");return}checkoutSummary.innerHTML=cart.map(item=>`<div class="checkout-row"><span>${item.name} × ${item.quantity}</span><strong>PKR ${(item.price*item.quantity).toLocaleString()}</strong></div>`).join("");const total=cart.reduce((sum,item)=>sum+item.price*item.quantity,0);checkoutTotal.textContent=`PKR ${total.toLocaleString()}`;checkoutModal.classList.add("open")});
checkoutClose.addEventListener("click",()=>checkoutModal.classList.remove("open"));checkoutModal.addEventListener("click",event=>{if(event.target===checkoutModal)checkoutModal.classList.remove("open")});
placeOrder.addEventListener("click",()=>{alert("Demo order successful! No real order was placed.");cart=[];updateCart();checkoutModal.classList.remove("open");closeCart()});
const reviews=[{text:"The coffee is excellent and the atmosphere is exactly what I want from a weekend café.",name:"Sarah M.",location:"Lahore"},{text:"Beautiful space, friendly staff and probably the best Spanish latte I've had in Lahore.",name:"Hamza R.",location:"Lahore"},{text:"Perfect place to work for a few hours. Great coffee and a really relaxed atmosphere.",name:"Ayesha K.",location:"Lahore"}];let reviewIndex=0;const reviewContent=document.getElementById("review-content");
function renderReview(){const review=reviews[reviewIndex];reviewContent.innerHTML=`<div class="stars">★★★★★</div><blockquote>“${review.text}”</blockquote><strong>${review.name}</strong><span>${review.location}</span>`}
document.getElementById("review-next").addEventListener("click",()=>{reviewIndex=(reviewIndex+1)%reviews.length;renderReview()});document.getElementById("review-prev").addEventListener("click",()=>{reviewIndex=(reviewIndex-1+reviews.length)%reviews.length;renderReview()});
document.querySelectorAll(".faq-question").forEach(question=>question.addEventListener("click",()=>{const item=question.parentElement,answer=item.querySelector(".faq-answer"),isOpen=item.classList.contains("open");document.querySelectorAll(".faq-item").forEach(otherItem=>{otherItem.classList.remove("open");otherItem.querySelector(".faq-answer").style.maxHeight=null});if(!isOpen){item.classList.add("open");answer.style.maxHeight=answer.scrollHeight+"px"}}));
const lightbox=document.getElementById("lightbox"),lightboxImage=document.getElementById("lightbox-image"),lightboxClose=document.getElementById("lightbox-close");
document.querySelectorAll(".gallery-item").forEach(item=>item.addEventListener("click",()=>{const image=item.querySelector("img");lightboxImage.src=image.src;lightboxImage.alt=image.alt;lightbox.classList.add("open");document.body.classList.add("no-scroll")}));
function closeLightbox(){lightbox.classList.remove("open");document.body.classList.remove("no-scroll")}
lightboxClose.addEventListener("click",closeLightbox);lightbox.addEventListener("click",event=>{if(event.target===lightbox)closeLightbox()});
document.addEventListener("keydown",event=>{if(event.key==="Escape"){closeCart();checkoutModal.classList.remove("open");closeLightbox()}});
const backTop=document.getElementById("back-top");window.addEventListener("scroll",()=>{backTop.classList.toggle("visible",window.scrollY>600)});backTop.addEventListener("click",()=>window.scrollTo({top:0,behavior:"smooth"}));
updateCart();renderReview();
